# specify dependencies for myblender.org operation (see also apt.txt
# for the full set)
channels:
    - conda-forge
dependencies:
    - cython
    - fresnel
    - freud
    - hoomd
    - pyglet
    - pip
    - pip:
      - matplotlib
      - pythreejs
      - git+https://github.com/vispy/vispy
      - plato-draw
      - gtar
      - git+https://github.com/klarh/flowws
      - git+https://github.com/klarh/hoomd_flowws
